travel_wishlist = ["Tokyo", "Paris", "New York", "Sydney", "Rio de Janeiro"]
print(f"Original travel wishlist: {travel_wishlist}")
sorted_wishlist = sorted(travel_wishlist)
print(f"Sorted travel wishlist (temporary): {sorted_wishlist}")
print(f"Original travel wishlist (unchanged): {travel_wishlist}")
sorted_wishlist = sorted(travel_wishlist, reverse=True)
print(f"Sorted travel wishlist in reverse order (temporary): {sorted_wishlist}")
travel_wishlist.reverse()
print(f"Travel wishlist after reversing: {travel_wishlist}")
travel_wishlist.reverse()
print(f"Travel wishlist after reversing again: {travel_wishlist}")
travel_wishlist.sort()
print(f"Travel wishlist after sorting: {travel_wishlist}")
travel_wishlist.sort(reverse=True)
print(f"Travel wishlist after sorting in reverse order: {travel_wishlist}")